name: ci

on: [push]

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up node env
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Compile typescript code
        run: npm run build

      - name: Run tests
        run: npm run test:ci
